# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod/codemod/refs/heads/main/schemas/workflow.json

version: "1.0"
nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    steps:
      - name: Handle DEP0030 via transforming SlowBuffer usage to Buffer.allocUnsafeSlow()..
        js-ast-grep:
          js_file: src/workflow.ts
          base_path: .
          include:
            - "**/*.js"
            - "**/*.jsx"
            - "**/*.mjs"
            - "**/*.cjs"
            - "**/*.cts"
            - "**/*.mts"
            - "**/*.ts"
            - "**/*.tsx"
          exclude:
            - "**/node_modules/**"
          language: typescript
