version: "1"

nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    runtime:
      type: direct
    steps:
      - name: Handle DEP0191 via transforming `repl.builtinModules` usage to `module.builtinModules`.
        js-ast-grep:
          js_file: src/workflow.ts
          base_path: .
          include:
            - "**/*.js"
            - "**/*.jsx"
            - "**/*.mjs"
            - "**/*.cjs"
            - "**/*.cts"
            - "**/*.mts"
            - "**/*.ts"
            - "**/*.tsx"
          exclude:
            - "**/node_modules/**"
          language: typescript
