# yaml-language-server: $schema=https://json.schemastore.org/codecov.json

# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project: # https://docs.codecov.com/docs/commit-status
      default:
        flags:
          - package
        paths:
          - "recipes/"
        target: 90%
        threshold: 80%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false # post comment only when coverage changes
  require_base: false # [true :: must have a base report to post]
  require_head: true # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]

flags:
  package: # for monorepos
    carryforward: true
