version: "1"
nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    runtime:
      type: direct
    steps:
      - name: Handle DEPDEP0116 via transforming `url.parse` to `new URL()`
        js-ast-grep:
          js_file: src/url-parse.ts
          base_path: .
          include:
            - "**/*.js"
            - "**/*.jsx"
            - "**/*.mjs"
            - "**/*.cjs"
            - "**/*.cts"
            - "**/*.mts"
            - "**/*.ts"
            - "**/*.tsx"
          exclude:
            - "**/node_modules/**"
          language: typescript
      - name: Handle DEPDEP0116 via transforming `url.format` to `new URL().toString()`
        js-ast-grep:
          js_file: src/url-format.ts
          base_path: .
          include:
            - "**/*.js"
            - "**/*.jsx"
            - "**/*.mjs"
            - "**/*.cjs"
            - "**/*.cts"
            - "**/*.mts"
            - "**/*.ts"
            - "**/*.tsx"
          exclude:
            - "**/node_modules/**"
          language: typescript
      - name: Clean up import statements + require calls
        js-ast-grep:
          js_file: src/import-process.ts
          base_path: .
          include:
            - "**/*.js"
            - "**/*.jsx"
            - "**/*.mjs"
            - "**/*.cjs"
            - "**/*.cts"
            - "**/*.mts"
            - "**/*.ts"
            - "**/*.tsx"
          exclude:
            - "**/node_modules/**"
