# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod-com/codemod/refs/heads/main/schemas/workflow.json

version: "1"

nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    runtime:
      type: direct
    steps:
      - name: Migrates Tape tests to Node.js native test runner
        js-ast-grep:
          js_file: src/workflow.ts
          base_path: .
          include:
            - "**/*.cjs"
            - "**/*.js"
            - "**/*.jsx"
            - "**/*.mjs"
            - "**/*.ts"
            - "**/*.tsx"

  - id: remove-dependencies
    name: Remove chalk dependency
    type: automatic
    steps:
      - name: Detect package manager and remove chalk dependency
        js-ast-grep:
          js_file: src/remove-dependencies.ts
          base_path: .
          include:
            - "**/package.json"
          exclude:
            - "**/node_modules/**"
          language: typescript
          capabilities:
            - child_process
            - fs
